# Generated by Django 4.0 on 2022-01-04 03:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0002_bid_created_comment_created_comment_modified_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='image',
            field=models.URLField(default='https://veohops.com/wp-content/uploads/2016/09/45.jpg'),
            preserve_default=False,
        ),
    ]
