# Generated by Django 4.0 on 2022-01-06 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0008_alter_user_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='listing',
            name='terminated',
            field=models.BooleanField(default=False),
        ),
    ]
