# Generated by Django 4.0 on 2022-01-07 03:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('auctions', '0009_listing_terminated'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='body',
            new_name='message',
        ),
    ]
